
INSERT INTO `t_corp` VALUES ('1', '1', '1', '001', '公司01', 'XX市XX街道', '1', '1', '1', '1', '1', '36526', '43230', '1000001', '张三', '1', '500', '37031', '长期', '计算机软件', '203545264', '15300001011', 'www.zhang3.com', 'zhang3@xx.com', '300', '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES ('2', '2', '2', '002', '公司02', 'XX市XX街道', '2', '2', '2', '2', '2', '36526', '43230', '1000002', '李四', '1', '1000', '37031', '长期', '硬件', '584534515', '15300001002', 'www.li4.com', 'li4@xx.com', '500', '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES ('3', '3', '3', '003', '公司03', 'XX市XX街道', '3', '3', '3', '3', '3', '36526', '43231', '1000003', '王五', '32874', '800', '37031', '长期', '半导体', '123515122', '15300001003', 'www.wang5.com', 'wang5@xx.com', '400', '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES ('4', '4', '4', '004', '子公司01', 'XX市XX街道', '4', '4', '4', '4', '4', '36526', '43230', '1000004', '张三', '1', '100', '37031', '长期', '网络安全', '223834825', '15300000997', 'www.zhang4.com', 'zhang4@xx.com', '100', '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES ('5', '5', '5', '005', '子公司02', 'XX市XX街道', '5', '5', '5', '5', '5', '36526', '43230', '1000005', '李四', '1', '200', '37031', '长期', '架构', '183819754', '15300000993', 'www.li5.com', 'li5@xx.com', '200', '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');
INSERT INTO `t_corp` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, '', '', '', '', '', '', '', null, '', '', '', '', '', '', '');


-- ----------------------------
-- Records of t_corp_dist
-- ----------------------------
INSERT INTO `t_corp_dist` VALUES ('1', '1', '1', '001', '子公司01', '', null, null, null, 'XX省XX市', '张一三', '网络安全', '2000/1/1', '2000/5/1', '', '');
INSERT INTO `t_corp_dist` VALUES ('2', '2', '2', '002', '子公司02', '', null, null, null, 'XX省XX市', '张一五', '架构', '2000/1/1', '2000/5/1', '', '');

-- ----------------------------
-- Table structure for `t_corp_pertains`
-- ----------------------------

-- ----------------------------
-- Records of t_corp_pertains
-- ----------------------------
INSERT INTO `t_corp_pertains` VALUES ('1', '1', '1', '身份证', '员工01', '总经理', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES ('2', '2', '2', '身份证', '员工02', '总经理', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES ('3', '3', '3', '身份证', '员工03', '总经理', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES ('4', '4', '4', '身份证', '员工04', '总经理', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES ('5', '5', '5', '身份证', '员工05', '总经理', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES ('6', '6', '6', '身份证', '员工06', '董事长', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES ('7', '7', '7', '身份证', '员工07', '董事长', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES ('8', '8', '8', '身份证', '员工08', '董事长', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES ('9', '9', '9', '身份证', '员工09', '董事长', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES ('10', '10', '10', '身份证', '员工10', '董事长', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES ('11', '11', '11', '身份证', '员工11', '董事长', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES ('12', '12', '12', '身份证', '员工12', '董事长', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES ('13', '13', '13', '身份证', '员工13', '董事长', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES ('14', '14', '14', '身份证', '员工14', '董事长', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES ('15', '15', '15', '身份证', '员工15', '董事长', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES ('16', '16', '16', '身份证', '员工16', '高管', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES ('17', '17', '17', '身份证', '员工17', '高管', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES ('18', '18', '18', '身份证', '员工18', '高管', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES ('19', '19', '19', '身份证', '员工19', '高管', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES ('20', '20', '20', '身份证', '员工20', '高管', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES ('21', '21', '21', '身份证', '员工21', '高管', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES ('22', '22', '22', '身份证', '员工22', '高管', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES ('23', '23', '23', '身份证', '员工23', '高管', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES ('24', '24', '24', '身份证', '员工24', '高管', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES ('25', '25', '25', '身份证', '员工25', '高管', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES ('26', '26', '26', '身份证', '员工26', '高管', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES ('27', '27', '27', '身份证', '员工27', '高管', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES ('28', '28', '28', '身份证', '员工28', '高管', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES ('29', '29', '29', '身份证', '员工29', '高管', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `t_corp_pertains` VALUES (null, null, null, '', '', '', '', '', '', '', '', '', '', '');

-- ----------------------------
-- Table structure for `t_corp_stock`
-- ----------------------------

INSERT INTO `t_corp_stock` VALUES ('1', '1', '1', '自然人', '中国', '身份证', '1001', '张一一', null, '200', null, null, '0.4', null, null, '');
INSERT INTO `t_corp_stock` VALUES ('2', '2', '2', '公司', '中国', '企业ID', '1002', '公司02', null, '100', null, null, '0.2', null, null, '');
INSERT INTO `t_corp_stock` VALUES ('3', '3', '3', '自然人', '中国', '身份证', '1003', '张一二', null, '50', null, null, '0.1', null, null, '');
INSERT INTO `t_corp_stock` VALUES ('4', '4', '4', '自然人', '中国', '身份证', '1004', '李一一', null, '300', null, null, '0.3', null, null, '');
INSERT INTO `t_corp_stock` VALUES ('5', '5', '5', '自然人', '中国', '身份证', '1005', '李一二', null, '500', null, null, '0.5', null, null, '');
INSERT INTO `t_corp_stock` VALUES ('6', '6', '6', '公司', '中国', '企业ID', '1006', '公司03', null, '200', null, null, '0.2', null, null, '');
INSERT INTO `t_corp_stock` VALUES ('7', '7', '7', '自然人', '中国', '身份证', '1007', '王一一', null, '400', null, null, '0.5', null, null, '');
INSERT INTO `t_corp_stock` VALUES ('8', '8', '8', '自然人', '中国', '身份证', '1008', '王一二', null, '300', null, null, '0.375', null, null, '');
INSERT INTO `t_corp_stock` VALUES ('9', '9', '9', '自然人', '中国', '身份证', '1009', '王一三', null, '100', null, null, '0.125', null, null, '');
INSERT INTO `t_corp_stock` VALUES ('10', '10', '10', '公司', '中国', '企业ID', '1010', '子公司01', null, '100', null, null, '1', null, null, '');
INSERT INTO `t_corp_stock` VALUES ('11', '11', '11', '公司', '中国', '企业ID', '1011', '子公司02', null, '200', null, null, '1', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');
INSERT INTO `t_corp_stock` VALUES (null, null, null, '', '', '', '', '', null, null, null, null, '', null, null, '');

-- ----------------------------
-- Table structure for `t_m_corp_corp_dist`
-- ----------------------------

-- ----------------------------
-- Records of t_m_corp_corp_dist
-- ----------------------------
INSERT INTO `t_m_corp_corp_dist` VALUES ('1', '1', '1', '1', '1', '1');
INSERT INTO `t_m_corp_corp_dist` VALUES ('1', '1', '1', '2', '2', '2');
INSERT INTO `t_m_corp_corp_dist` VALUES (null, null, null, null, null, null);
INSERT INTO `t_m_corp_corp_dist` VALUES (null, null, null, null, null, null);
INSERT INTO `t_m_corp_corp_dist` VALUES (null, null, null, null, null, null);
INSERT INTO `t_m_corp_corp_dist` VALUES (null, null, null, null, null, null);
INSERT INTO `t_m_corp_corp_dist` VALUES (null, null, null, null, null, null);
INSERT INTO `t_m_corp_corp_dist` VALUES (null, null, null, null, null, null);
INSERT INTO `t_m_corp_corp_dist` VALUES (null, null, null, null, null, null);
INSERT INTO `t_m_corp_corp_dist` VALUES (null, null, null, null, null, null);
INSERT INTO `t_m_corp_corp_dist` VALUES (null, null, null, null, null, null);
INSERT INTO `t_m_corp_corp_dist` VALUES (null, null, null, null, null, null);
INSERT INTO `t_m_corp_corp_dist` VALUES (null, null, null, null, null, null);
INSERT INTO `t_m_corp_corp_dist` VALUES (null, null, null, null, null, null);
INSERT INTO `t_m_corp_corp_dist` VALUES (null, null, null, null, null, null);
INSERT INTO `t_m_corp_corp_dist` VALUES (null, null, null, null, null, null);
INSERT INTO `t_m_corp_corp_dist` VALUES (null, null, null, null, null, null);
INSERT INTO `t_m_corp_corp_dist` VALUES (null, null, null, null, null, null);
INSERT INTO `t_m_corp_corp_dist` VALUES (null, null, null, null, null, null);
INSERT INTO `t_m_corp_corp_dist` VALUES (null, null, null, null, null, null);
INSERT INTO `t_m_corp_corp_dist` VALUES (null, null, null, null, null, null);
INSERT INTO `t_m_corp_corp_dist` VALUES (null, null, null, null, null, null);
INSERT INTO `t_m_corp_corp_dist` VALUES (null, null, null, null, null, null);
INSERT INTO `t_m_corp_corp_dist` VALUES (null, null, null, null, null, null);
INSERT INTO `t_m_corp_corp_dist` VALUES (null, null, null, null, null, null);
INSERT INTO `t_m_corp_corp_dist` VALUES (null, null, null, null, null, null);
INSERT INTO `t_m_corp_corp_dist` VALUES (null, null, null, null, null, null);
INSERT INTO `t_m_corp_corp_dist` VALUES (null, null, null, null, null, null);
INSERT INTO `t_m_corp_corp_dist` VALUES (null, null, null, null, null, null);
INSERT INTO `t_m_corp_corp_dist` VALUES (null, null, null, null, null, null);
INSERT INTO `t_m_corp_corp_dist` VALUES (null, null, null, null, null, null);
INSERT INTO `t_m_corp_corp_dist` VALUES (null, null, null, null, null, null);
INSERT INTO `t_m_corp_corp_dist` VALUES (null, null, null, null, null, null);
INSERT INTO `t_m_corp_corp_dist` VALUES (null, null, null, null, null, null);
INSERT INTO `t_m_corp_corp_dist` VALUES (null, null, null, null, null, null);
INSERT INTO `t_m_corp_corp_dist` VALUES (null, null, null, null, null, null);
INSERT INTO `t_m_corp_corp_dist` VALUES (null, null, null, null, null, null);
INSERT INTO `t_m_corp_corp_dist` VALUES (null, null, null, null, null, null);
INSERT INTO `t_m_corp_corp_dist` VALUES (null, null, null, null, null, null);
INSERT INTO `t_m_corp_corp_dist` VALUES (null, null, null, null, null, null);
INSERT INTO `t_m_corp_corp_dist` VALUES (null, null, null, null, null, null);
INSERT INTO `t_m_corp_corp_dist` VALUES (null, null, null, null, null, null);
INSERT INTO `t_m_corp_corp_dist` VALUES (null, null, null, null, null, null);
INSERT INTO `t_m_corp_corp_dist` VALUES (null, null, null, null, null, null);
INSERT INTO `t_m_corp_corp_dist` VALUES (null, null, null, null, null, null);
INSERT INTO `t_m_corp_corp_dist` VALUES (null, null, null, null, null, null);
INSERT INTO `t_m_corp_corp_dist` VALUES (null, null, null, null, null, null);
INSERT INTO `t_m_corp_corp_dist` VALUES (null, null, null, null, null, null);
INSERT INTO `t_m_corp_corp_dist` VALUES (null, null, null, null, null, null);
INSERT INTO `t_m_corp_corp_dist` VALUES (null, null, null, null, null, null);
INSERT INTO `t_m_corp_corp_dist` VALUES (null, null, null, null, null, null);
INSERT INTO `t_m_corp_corp_dist` VALUES (null, null, null, null, null, null);
INSERT INTO `t_m_corp_corp_dist` VALUES (null, null, null, null, null, null);
INSERT INTO `t_m_corp_corp_dist` VALUES (null, null, null, null, null, null);
INSERT INTO `t_m_corp_corp_dist` VALUES (null, null, null, null, null, null);
INSERT INTO `t_m_corp_corp_dist` VALUES (null, null, null, null, null, null);
INSERT INTO `t_m_corp_corp_dist` VALUES (null, null, null, null, null, null);
INSERT INTO `t_m_corp_corp_dist` VALUES (null, null, null, null, null, null);
INSERT INTO `t_m_corp_corp_dist` VALUES (null, null, null, null, null, null);
INSERT INTO `t_m_corp_corp_dist` VALUES (null, null, null, null, null, null);
INSERT INTO `t_m_corp_corp_dist` VALUES (null, null, null, null, null, null);
INSERT INTO `t_m_corp_corp_dist` VALUES (null, null, null, null, null, null);
INSERT INTO `t_m_corp_corp_dist` VALUES (null, null, null, null, null, null);
INSERT INTO `t_m_corp_corp_dist` VALUES (null, null, null, null, null, null);
INSERT INTO `t_m_corp_corp_dist` VALUES (null, null, null, null, null, null);
INSERT INTO `t_m_corp_corp_dist` VALUES (null, null, null, null, null, null);
INSERT INTO `t_m_corp_corp_dist` VALUES (null, null, null, null, null, null);
INSERT INTO `t_m_corp_corp_dist` VALUES (null, null, null, null, null, null);
INSERT INTO `t_m_corp_corp_dist` VALUES (null, null, null, null, null, null);
INSERT INTO `t_m_corp_corp_dist` VALUES (null, null, null, null, null, null);
INSERT INTO `t_m_corp_corp_dist` VALUES (null, null, null, null, null, null);
INSERT INTO `t_m_corp_corp_dist` VALUES (null, null, null, null, null, null);
INSERT INTO `t_m_corp_corp_dist` VALUES (null, null, null, null, null, null);
INSERT INTO `t_m_corp_corp_dist` VALUES (null, null, null, null, null, null);
INSERT INTO `t_m_corp_corp_dist` VALUES (null, null, null, null, null, null);
INSERT INTO `t_m_corp_corp_dist` VALUES (null, null, null, null, null, null);
INSERT INTO `t_m_corp_corp_dist` VALUES (null, null, null, null, null, null);
INSERT INTO `t_m_corp_corp_dist` VALUES (null, null, null, null, null, null);
INSERT INTO `t_m_corp_corp_dist` VALUES (null, null, null, null, null, null);
INSERT INTO `t_m_corp_corp_dist` VALUES (null, null, null, null, null, null);
INSERT INTO `t_m_corp_corp_dist` VALUES (null, null, null, null, null, null);
INSERT INTO `t_m_corp_corp_dist` VALUES (null, null, null, null, null, null);
INSERT INTO `t_m_corp_corp_dist` VALUES (null, null, null, null, null, null);
INSERT INTO `t_m_corp_corp_dist` VALUES (null, null, null, null, null, null);
INSERT INTO `t_m_corp_corp_dist` VALUES (null, null, null, null, null, null);
INSERT INTO `t_m_corp_corp_dist` VALUES (null, null, null, null, null, null);
INSERT INTO `t_m_corp_corp_dist` VALUES (null, null, null, null, null, null);
INSERT INTO `t_m_corp_corp_dist` VALUES (null, null, null, null, null, null);
INSERT INTO `t_m_corp_corp_dist` VALUES (null, null, null, null, null, null);
INSERT INTO `t_m_corp_corp_dist` VALUES (null, null, null, null, null, null);
INSERT INTO `t_m_corp_corp_dist` VALUES (null, null, null, null, null, null);
INSERT INTO `t_m_corp_corp_dist` VALUES (null, null, null, null, null, null);
INSERT INTO `t_m_corp_corp_dist` VALUES (null, null, null, null, null, null);
INSERT INTO `t_m_corp_corp_dist` VALUES (null, null, null, null, null, null);
INSERT INTO `t_m_corp_corp_dist` VALUES (null, null, null, null, null, null);
INSERT INTO `t_m_corp_corp_dist` VALUES (null, null, null, null, null, null);
INSERT INTO `t_m_corp_corp_dist` VALUES (null, null, null, null, null, null);
INSERT INTO `t_m_corp_corp_dist` VALUES (null, null, null, null, null, null);
INSERT INTO `t_m_corp_corp_dist` VALUES (null, null, null, null, null, null);
INSERT INTO `t_m_corp_corp_dist` VALUES (null, null, null, null, null, null);
INSERT INTO `t_m_corp_corp_dist` VALUES (null, null, null, null, null, null);
INSERT INTO `t_m_corp_corp_dist` VALUES (null, null, null, null, null, null);
INSERT INTO `t_m_corp_corp_dist` VALUES (null, null, null, null, null, null);
INSERT INTO `t_m_corp_corp_dist` VALUES (null, null, null, null, null, null);
INSERT INTO `t_m_corp_corp_dist` VALUES (null, null, null, null, null, null);
INSERT INTO `t_m_corp_corp_dist` VALUES (null, null, null, null, null, null);
INSERT INTO `t_m_corp_corp_dist` VALUES (null, null, null, null, null, null);
INSERT INTO `t_m_corp_corp_dist` VALUES (null, null, null, null, null, null);
INSERT INTO `t_m_corp_corp_dist` VALUES (null, null, null, null, null, null);
INSERT INTO `t_m_corp_corp_dist` VALUES (null, null, null, null, null, null);
INSERT INTO `t_m_corp_corp_dist` VALUES (null, null, null, null, null, null);
INSERT INTO `t_m_corp_corp_dist` VALUES (null, null, null, null, null, null);
INSERT INTO `t_m_corp_corp_dist` VALUES (null, null, null, null, null, null);
INSERT INTO `t_m_corp_corp_dist` VALUES (null, null, null, null, null, null);
INSERT INTO `t_m_corp_corp_dist` VALUES (null, null, null, null, null, null);
INSERT INTO `t_m_corp_corp_dist` VALUES (null, null, null, null, null, null);
INSERT INTO `t_m_corp_corp_dist` VALUES (null, null, null, null, null, null);
INSERT INTO `t_m_corp_corp_dist` VALUES (null, null, null, null, null, null);
INSERT INTO `t_m_corp_corp_dist` VALUES (null, null, null, null, null, null);
INSERT INTO `t_m_corp_corp_dist` VALUES (null, null, null, null, null, null);
INSERT INTO `t_m_corp_corp_dist` VALUES (null, null, null, null, null, null);
INSERT INTO `t_m_corp_corp_dist` VALUES (null, null, null, null, null, null);
INSERT INTO `t_m_corp_corp_dist` VALUES (null, null, null, null, null, null);
INSERT INTO `t_m_corp_corp_dist` VALUES (null, null, null, null, null, null);
INSERT INTO `t_m_corp_corp_dist` VALUES (null, null, null, null, null, null);
INSERT INTO `t_m_corp_corp_dist` VALUES (null, null, null, null, null, null);
INSERT INTO `t_m_corp_corp_dist` VALUES (null, null, null, null, null, null);
INSERT INTO `t_m_corp_corp_dist` VALUES (null, null, null, null, null, null);

-- ----------------------------
-- Table structure for `t_m_corp_corp_pertains`
-- ----------------------------


-- ----------------------------
-- Records of t_m_corp_corp_pertains
-- ----------------------------
INSERT INTO `t_m_corp_corp_pertains` VALUES ('1', '1', '1', '1', '1', '1');
INSERT INTO `t_m_corp_corp_pertains` VALUES ('2', '2', '2', '2', '2', '2');
INSERT INTO `t_m_corp_corp_pertains` VALUES ('3', '3', '3', '3', '3', '3');
INSERT INTO `t_m_corp_corp_pertains` VALUES ('4', '4', '4', '4', '4', '4');
INSERT INTO `t_m_corp_corp_pertains` VALUES ('5', '5', '5', '5', '5', '5');
INSERT INTO `t_m_corp_corp_pertains` VALUES ('1', '1', '1', '6', '6', '6');
INSERT INTO `t_m_corp_corp_pertains` VALUES ('2', '2', '2', '7', '7', '7');
INSERT INTO `t_m_corp_corp_pertains` VALUES ('3', '3', '3', '8', '8', '8');
INSERT INTO `t_m_corp_corp_pertains` VALUES ('4', '4', '4', '9', '9', '9');
INSERT INTO `t_m_corp_corp_pertains` VALUES ('5', '5', '5', '10', '10', '10');
INSERT INTO `t_m_corp_corp_pertains` VALUES ('1', '1', '1', '11', '11', '11');
INSERT INTO `t_m_corp_corp_pertains` VALUES ('2', '2', '2', '12', '12', '12');
INSERT INTO `t_m_corp_corp_pertains` VALUES ('3', '3', '3', '13', '13', '13');
INSERT INTO `t_m_corp_corp_pertains` VALUES ('4', '4', '4', '14', '14', '14');
INSERT INTO `t_m_corp_corp_pertains` VALUES ('5', '5', '5', '15', '15', '15');
INSERT INTO `t_m_corp_corp_pertains` VALUES ('1', '1', '1', '16', '16', '16');
INSERT INTO `t_m_corp_corp_pertains` VALUES ('2', '2', '2', '17', '17', '17');
INSERT INTO `t_m_corp_corp_pertains` VALUES ('3', '3', '3', '18', '18', '18');
INSERT INTO `t_m_corp_corp_pertains` VALUES ('4', '4', '4', '19', '19', '19');
INSERT INTO `t_m_corp_corp_pertains` VALUES ('5', '5', '5', '20', '20', '20');
INSERT INTO `t_m_corp_corp_pertains` VALUES ('1', '1', '1', '21', '21', '21');
INSERT INTO `t_m_corp_corp_pertains` VALUES ('2', '2', '2', '22', '22', '22');
INSERT INTO `t_m_corp_corp_pertains` VALUES ('3', '3', '3', '23', '23', '23');
INSERT INTO `t_m_corp_corp_pertains` VALUES ('4', '4', '4', '24', '24', '24');
INSERT INTO `t_m_corp_corp_pertains` VALUES ('5', '5', '5', '25', '25', '25');
INSERT INTO `t_m_corp_corp_pertains` VALUES ('1', '1', '1', '26', '26', '26');
INSERT INTO `t_m_corp_corp_pertains` VALUES ('2', '2', '2', '27', '27', '27');
INSERT INTO `t_m_corp_corp_pertains` VALUES ('3', '3', '3', '28', '28', '28');
INSERT INTO `t_m_corp_corp_pertains` VALUES ('4', '4', '4', '29', '29', '29');

-- ----------------------------
-- Table structure for `t_m_corp_corp_stock`
-- ----------------------------

-- ----------------------------
-- Records of t_m_corp_corp_stock
-- ----------------------------
INSERT INTO `t_m_corp_corp_stock` VALUES ('1', '1', '1', '1', '1', '1');
INSERT INTO `t_m_corp_corp_stock` VALUES ('1', '1', '1', '2', '2', '2');
INSERT INTO `t_m_corp_corp_stock` VALUES ('1', '1', '1', '3', '3', '3');
INSERT INTO `t_m_corp_corp_stock` VALUES ('2', '2', '2', '4', '4', '4');
INSERT INTO `t_m_corp_corp_stock` VALUES ('2', '2', '2', '5', '5', '5');
INSERT INTO `t_m_corp_corp_stock` VALUES ('2', '2', '2', '6', '6', '6');
INSERT INTO `t_m_corp_corp_stock` VALUES ('3', '3', '3', '7', '7', '7');
INSERT INTO `t_m_corp_corp_stock` VALUES ('3', '3', '3', '8', '8', '8');
INSERT INTO `t_m_corp_corp_stock` VALUES ('3', '3', '3', '9', '9', '9');
